version: '3'
services:
  keycloak:
    image: sleighzy/keycloak:latest
    container_name: keycloak
    ports:
      - "4000:8080"
    volumes:
      - ./data:/opt/jboss/keycloak/standalone/data
    environment:
     KEYCLOAK_USER: admin
     KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}